name: Build Votekick Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Mod
      run: dotnet build --configuration Release --no-restore

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: VotekickMod
        path: bin/Release/netstandard2.1/VotekickMod.dll
        if-no-files-found: error
        retention-days: 1
